config/routes.rb
Rails.application.routes.draw do

  get 'mailbox/inbox' => 'mailbox#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailbox#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailbox#trash', as: :mailbox_trash

  devise_for :users
  resources :polls do
    resources :questions
    resources :replies, only: [ :new, :create ]
  end
  
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  
  root "polls#index"
  
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!

  def new
  end

  def create
    recipients = User.where(id: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    conversation.mark_as_read(current_user)
  end

  def reply
    current_user.reply_to_conversation(conversation, message_params[:body])
    flash[:notice] = "Your reply message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to mailbox_inbox_path
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to mailbox_inbox_path
  end

  private

  def message_params
    params.require(:message).permit(:body, :subject)
  end

  def conversation_params
    params.require(:conversation).permit(:subject, :body, recipients:[])
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.haml
.media
  .media-left
    %img.media-object{:src => "https://api.adorable.io/avatars/64/#{conversation.originator.id}"}
  .media-body
    %h4.media-heading
      = conversation.originator.email
      %br/
      %small
        %b Subject:
        = conversation.subject
      %br/
      %small
        %b Date:
        = conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p")
    = truncate conversation.messages.last.body, length: 145
    = link_to "View", conversation_path(conversation)

app/views/conversations/_form.html.haml
= form_for :conversation, url: :conversations, html: { class: "" } do |f|
  .form-group
    = f.label :recipients
    = f.select(:recipients, User.all.collect {|p| [ p.email, p.id ] }, {}, { multiple: true , class: "chosen-select form-control" })
  .form-group
    = f.label :subject
    = f.text_field :subject, placeholder: "Subject", class: "form-control"
  .form-group
    = f.label :message
    = f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4
  = f.submit "Send Message", class: "btn btn-success"

app/views/conversations/_messages.html.haml
- @receipts.each do |receipt|
  - message = receipt.message
  .media
    .media-left
      / user avators can go here
      %a{:href => "#"}
        %img.media-object{:src => "https://api.adorable.io/avatars/64/#{message.sender.id}"}/
    .media-body
      %h4.media-heading
        = message.sender.email
        %br/
        %small
          %b Subject:
          = message.subject
        %br/
        %small
          %b Date:
          = message.created_at.strftime("%A, %b %d, %Y at %I:%M%p")
      = message.body

app/views/conversations/new.html.haml
= render partial: 'mailbox/folder_view', locals: { is_conversation: true }

app/views/conversations/show.html.haml
.row
  .spacer
  .col-md-4
    .panel.panel-default
      .panel-body
        = render 'mailbox/folders'
  .col-md-8
    .panel.panel-default
      .panel-body
        = render partial: 'messages'
      .panel-footer
        / Reply Form
        = form_for :message, url: reply_conversation_path(@conversation) do |f|
          .form-group
            = f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control"
          = f.submit "Reply", class: 'btn btn-primary pull-right'
        .clearfix
.row
  .col-md-4
  .col-md-8.text-center
    - if @conversation.is_trashed?(current_user)
      = link_to 'Untrash', untrash_conversation_path(@conversation), class: 'btn btn-info', method: :post
    - else
      = link_to 'Move to trash', trash_conversation_path(@conversation), class: 'btn btn-danger', method: :post, |
        data: {confirm: 'Are you sure?'}   