config/routes.rb
Rails.application.routes.draw do

  get 'mailbox/inbox' => 'mailbox#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailbox#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailbox#trash', as: :mailbox_trash

  devise_for :users
  resources :polls do
    resources :questions
    resources :replies, only: [ :new, :create ]
  end
  
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  
  root "polls#index"
  
end

app/controllers/mailbox_controller.rb
class MailboxController < ApplicationController
  before_action :authenticate_user!

  def inbox
    @inbox = mailbox.inbox
    @active = :inbox
  end

  def sent
    @sent = mailbox.sentbox
    @active = :sent
  end

  def trash
    @trash = mailbox.trash
    @active = :trash
  end
  
end

app/helpers/mailbox_helper.rb
module MailboxHelper

end

app/views/mailbox/_folder_view.html.haml
.row
  .col-md-4
    .panel.panel-default
      .panel-body
        = render 'mailbox/folders'
  .col-md-8
    .panel.panel-default
      .panel-body
        - if is_conversation
          = render 'conversations/form'
        - else
          = render partial: 'conversations/conversation', collection: messages

app/views/mailbox/_folders.html.haml
%ul.nav.nav-pills.nav-stacked
  %li{:class => "bg-success"}
    = link_to new_conversation_path do
      %em.fa.fa-paper-plane-o.fa-lg
      %span Compose
  %li{:class => active_page(:inbox)}
    = link_to mailbox_inbox_path do
      %span.badge.badge-danger.pull-right= unread_messages_count
      %em.fa.fa-inbox.fa-lg
      %span Inbox
  %li{:class => active_page(:sent)}
    = link_to mailbox_sent_path do
      %em.fa.fa-paper-plane-o.fa-lg
      %span Sent
  %li{:class => active_page(:trash)}
    = link_to mailbox_trash_path do
      %em.fa.fa-trash-o.fa-lg
      %span Trash

app/views/mailbox/inbox.html.haml
= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @inbox }

app/views/mailbox/sent.html.haml
= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @sent }

app/views/mailbox/trash.html.haml
= render partial: 'mailbox/folder_view', locals: { is_conversation: false, messages: @trash }