config/routes.rb
Rails.application.routes.draw do

  get 'mailbox/inbox' => 'mailbox#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailbox#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailbox#trash', as: :mailbox_trash

  devise_for :users
  resources :polls do
    resources :questions
    resources :replies, only: [ :new, :create ]
  end
  
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  
  root "polls#index"
  
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  validates_presence_of :title
  has_many :questions, dependent: :destroy
  has_many :replies, dependent: :destroy
  
  def serialize_for_graph
    PollSerializer.count_per_day(self).to_json
end
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  before_action :set_poll, only: [:show, :edit, :update, :destroy]
  before_action :admin!, except: [:index]
  # GET /polls
  # GET /polls.json
  def index
    @polls = Poll.all
  end

  # GET /polls/1
  # GET /polls/1.json
  def show
  end

  # GET /polls/new
  def new
    @poll = Poll.new
  end

  # GET /polls/1/edit
  def edit
  end

  # POST /polls
  # POST /polls.json
  def create
    @poll = Poll.new(poll_params)

    respond_to do |format|
      if @poll.save
        format.html { redirect_to @poll, flash: { success: 'Poll was successfully created.' } }
        format.json { render :show, status: :created, location: @poll }
      else
        format.html { render :new }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /polls/1
  # PATCH/PUT /polls/1.json
  def update
    respond_to do |format|
      if @poll.update(poll_params)
        format.html { redirect_to @poll, notice: 'Poll was successfully updated.' }
        format.json { render :show, status: :ok, location: @poll }
      else
        format.html { render :edit }
        format.json { render json: @poll.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /polls/1
  # DELETE /polls/1.json
  def destroy
    @poll.destroy
    respond_to do |format|
      format.html { redirect_to polls_url, flash: { error: 'Poll was successfully destroyed.' }  }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_poll
      @poll = Poll.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def poll_params
      params.require(:poll).permit(:title)
    end
    
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/polls/_form.html.haml
= form_for @poll do |f|
  - if @poll.errors.any?
    #error_explanation
      %h2= "#{pluralize(@poll.errors.count, "error")} prohibited this poll from being saved:"
      %ul
        - @poll.errors.full_messages.each do |msg|
          %li= msg

  %p
    = f.label :title
    = f.text_field :title, class: "form-control", placeholder: "Enter title here"
  .actions
    %p
      = f.submit 'Save', class: "btn btn-primary"

app/views/polls/_stats.html.haml
#polls_per_day
  :javascript
    (function($) {
      $(function() {
        var selector = "#polls_per_day";
        var data = #{@poll.serialize_for_graph};
        Graph.column(selector,data);
      });
    })(jQuery);
#answers_per_question
  -@poll.questions.each do |question|
    -if question.kind == "choice"
      .col-md-4{id: "answers-per-question-#{question.id}"}
      :javascript
        (function($) {
          $(function() {
            var selector = "#answers-per-question-#{question.id}";
            var data = #{question.serialize_for_graph};
            Graph.pie(selector,data);
          });
        })(jQuery);
-content_for :footer do
  :javascript
    google.charts.setOnLoadCallback(function() {
      Graph.instances.forEach(function(instance) {
        instance.render();
      });
    });

app/views/polls/edit.html.haml
%h1 Editing poll

= render 'form'

= link_to 'Show', @poll
\|
= link_to 'Back', polls_path

app/views/polls/index.html.haml
%table.table.table-hover
  %thead
    %tr
      %th.col-md-7 Poll title
      %th.col-md-1 Number of questions      
      %th.col-md-1 Number of replies
      %th.col-md-3 Option
  %tbody
    - @polls.each do |poll|
      %tr
        %td.col-md-7
          =link_to poll.title, poll
        %td.col-md-1.text-center
          =Question.where(poll_id: poll.id).count
        %td.col-md-1.text-center
          =Reply.where(poll_id: poll.id).count
        %td.col-md-3.text-center
          =link_to 'Edit', edit_poll_path(poll), class: "btn btn-warning" if admin?
          =link_to 'Destroy', poll, :method => :delete, class: "btn btn-danger", :data => { :confirm => 'Are you sure?' } if admin?
          =link_to 'Answer', new_poll_reply_path(poll), class: "btn btn-default" if current_user unless admin?
        
%p= link_to 'New Poll', new_poll_path, class: "btn btn-primary" if admin?

app/views/polls/new.html.haml
%h1 New poll

= render 'form'

= link_to 'Back', polls_path, class: "btn btn-default"

app/views/polls/show.html.haml
%h1= @poll.title

%div 
  %ul.nav.nav-tabs{:role => "tablist"}
    %li.active
      =link_to "Questions", "#tab-questions", data: { toggle: "tab" }
    %li
      =link_to "Replies", "#tab-replies", data: { toggle: "tab" }
    %li
      =link_to "Stats", "#tab-stats", data: { toggle: "tab" } 
  .tab-content
    #tab-questions.tab-pane.active{:role => "tabpanel"}
      %h2 Questions
      %ul 
        -@poll.questions.each do |question|
          %li
            =question.title
            %ul
              -question.possible_answers.each do |possible_answer|
                %li=possible_answer.title
      
      %p.btn-group
        = link_to 'Edit', edit_poll_path(@poll), class: "btn btn-default"
        = link_to 'Back', polls_path, class: "btn btn-default"
        = link_to 'Add question', new_poll_question_path(@poll), class: "btn btn-default"

    #tab-replies.tab-pane{:role => "tabpanel"}
      %h2 Replies
      -@poll.replies.each do |reply|
        .col-md-6
          .panel.panel-default
            .panel-heading.text-right
              =time_ago_in_words reply.created_at
              ago
            .panel-body
              %dl
                -reply.answers.each do |answer|
                  %dt=answer.question.title
                  %dd
                    =answer.value.present? ? answer.value : answer.possible_answer.title

    #tab-stats.tab-pane
      =render "stats"