config/routes.rb
Rails.application.routes.draw do

  get 'mailbox/inbox' => 'mailbox#inbox', as: :mailbox_inbox
  get 'mailbox/sent' => 'mailbox#sent', as: :mailbox_sent
  get 'mailbox/trash' => 'mailbox#trash', as: :mailbox_trash

  devise_for :users
  resources :polls do
    resources :questions
    resources :replies, only: [ :new, :create ]
  end
  
  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end
  
  root "polls#index"
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :mailbox, :conversation
  
  private
  
  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id]) 
  end
  
  protected
  
  def admin!
    authenticate_user!
    redirect_to root_path, alert: "You are not authorized to perform this operation." unless current_user.admin?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end

  def unread_messages_count
    mailbox.inbox(:unread => true).count(:id, :distinct => true)
  end

  def active_page(active_page)
    @active == active_page ? "active" : ""
  end

  def admin?
    current_user && current_user.admin?
  end
  
end

app/views/application/_nav.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      =link_to "Dedicated polling system", root_path, class: "navbar-brand"
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav
        -while false
          %li.active
            =link_to "Polls", polls_path
          %li
            %a{:href => "#"} Link
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Dropdown
              %span.caret
            %ul.dropdown-menu
              %li
                %a{:href => "#"} Action
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider{:role => "separator"}
              %li
                %a{:href => "#"} Separated link
              %li.divider{:role => "separator"}
              %li
                %a{:href => "#"} One more separated link
      %form.navbar-form.navbar-left
        .form-group
          %input.form-control{:placeholder => "Search", :type => "text"}/
        %button.btn.btn-default{:type => "submit"} Submit
      %ul.nav.navbar-nav.navbar-right
        -if current_user
          %li 
            -if unread_messages_count > 0
              %li.bg-danger
                =link_to mailbox_inbox_path do
                  %span.glyphicon.glyphicon-inbox 
                  = "You have"
                  = unread_messages_count
                  = "unread messages in Inbox"
            -else
              %li
                =link_to mailbox_inbox_path do
                  %span.glyphicon.glyphicon-inbox 
                  Inbox
            %span.navbar-text Signed in as #{current_user.email}
            %li
              =link_to destroy_session_path('user'), method: :delete do
                %span.glyphicon.glyphicon-log-out
                Sign out
        -else
          %li
            =link_to new_session_path('user') do
              Sign in
              %span.glyphicon.glyphicon-log-in